import assert from 'node:assert/strict';
import {canTransition, transitionCase, validateClosure, deadEndFeedbackForCase, validateSharePackage, validateHandoffCase, HANDOFF_STATUSES, HANDOFF_OUTCOMES} from '../shared-handoffs.mjs';
assert.ok(HANDOFF_STATUSES.includes('delivered'));
assert.ok(HANDOFF_OUTCOMES.includes('service_completed'));
assert.equal(canTransition('delivered','accepted'), true);
assert.equal(canTransition('delivered','scheduled'), false);
assert.throws(()=>transitionCase({status:'delivered',version:2},'accepted',{actorType:'person',at:'2026-09-23T10:00:00Z'}),/partner_authority_required/);
assert.equal(validateClosure('other','').ok,false);
assert.equal(validateClosure('other','Documented special outcome').ok,true);
assert.equal(validateClosure('no_availability','').ok,true);
assert.deepEqual(deadEndFeedbackForCase({resourceId:'r1',closedOutcome:'no_availability'}),{resourceId:'r1',reason:'no_availability'});
assert.equal(deadEndFeedbackForCase({resourceId:'r1',closedOutcome:'service_completed'}),null);
const pkg={scope:'summary',summary:'Need food support'};
assert.equal(validateSharePackage(pkg).ok,true);
const original={id:'c1',status:'accepted',version:3,sharePackage:pkg,resourceId:'r1',partnerOrgId:'o1',createdAt:'2026-09-23T10:00:00Z',updatedAt:'2026-09-23T10:00:00Z'};
const next=transitionCase(original,'in_progress',{actorType:'partner',at:'2026-09-23T10:05:00Z'});
assert.deepEqual(next.sharePackage,original.sharePackage); assert.notEqual(next,original); assert.equal(next.version,4); assert.equal(original.version,3);
assert.equal(validateHandoffCase(next).ok,true);
console.log('handoff domain tests passed');
