import assert from 'node:assert/strict'; import {mkdtemp} from 'node:fs/promises'; import {join} from 'node:path'; import {tmpdir} from 'node:os';
import {createServer} from '../server.js'; import {createV4Runtime} from '../server/v4/api.js'; import {issueMagicLink} from '../server/v4/auth.js';
const dir=await mkdtemp(join(tmpdir(),'ws-v4-api-')); const runtime=createV4Runtime({dataDir:dir}); const now=new Date();
await runtime.partnerStore.upsertOrganization({id:'oa',name:'Org A',resourceIds:['r1'],status:'active',createdAt:now.toISOString(),updatedAt:now.toISOString()}); await runtime.partnerStore.upsertOrganization({id:'ob',name:'Org B',resourceIds:['r2'],status:'active',createdAt:now.toISOString(),updatedAt:now.toISOString()});
const ua=await runtime.partnerStore.upsertUser({id:'ua',partnerOrgId:'oa',email:'a@x.test',displayName:'A',role:'partner_manager',status:'active'}); const ub=await runtime.partnerStore.upsertUser({id:'ub',partnerOrgId:'ob',email:'b@x.test',displayName:'B',role:'partner_manager',status:'active'});
const server=createServer({v4Runtime:runtime}); await new Promise(r=>server.listen(0,'127.0.0.1',r)); const base=`http://127.0.0.1:${server.address().port}`;
const j=async(path,opt={})=>{const res=await fetch(base+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});let body={};try{body=await res.json()}catch{}return{res,body}};

const malformed=await fetch(base+'/api/v4/cases/preview',{method:'POST',headers:{'content-type':'application/json'},body:'{bad'}); assert.equal(malformed.status,400); const oversized=await fetch(base+'/api/v4/cases/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({story:{text:'x'.repeat(70000)},signals:[],priority:{},profile:{},consent:{shareScope:'summary'}})}); assert.equal(oversized.status,413);
const preview=await j('/api/v4/cases/preview',{method:'POST',body:JSON.stringify({story:{id:'s1',text:'Need food'},signals:[{domain:'food',status:'active'}],priority:{domain:'food'},profile:{displayName:'J'},consent:{shareScope:'summary'},resourceId:'r1',partnerOrgId:'oa'})}); assert.equal(preview.res.status,200); assert.equal(preview.body.sharePackage.scope,'summary');
const created=await j('/api/v4/cases',{method:'POST',body:JSON.stringify({sharePackage:preview.body.sharePackage,shareScope:preview.body.shareScope,personDisplayName:preview.body.personDisplayName,preferredContactMethod:preview.body.preferredContactMethod,storyId:'s1',resourceId:'r1',partnerOrgId:'oa',createdBy:{type:'person',id:null,displayName:'J'}})}); assert.equal(created.res.status,201); assert.ok(created.body.accessSecret); const cid=created.body.case.id;
const noSecret=await j(`/api/v4/cases/${cid}`); assert.ok([403,404].includes(noSecret.res.status)); assert.equal(JSON.stringify(noSecret.body).includes('Org A'),false);
const person=await j(`/api/v4/cases/${cid}`,{headers:{authorization:`Bearer ${created.body.accessSecret}`}}); assert.equal(person.res.status,200); assert.equal(person.body.case.status,'delivered'); assert.equal(person.res.headers.get('cache-control'),'no-store'); assert.equal(JSON.stringify(person.body).includes('accessSecretHash'),false);
const issued=await issueMagicLink({user:ua,sessionStore:runtime.sessionStore,now:new Date()}); const redeemed=await j('/api/v4/partner/session/redeem',{method:'POST',body:JSON.stringify({token:issued.token})}); assert.equal(redeemed.res.status,200); assert.ok(redeemed.body.sessionToken); const bearer={authorization:`Bearer ${redeemed.body.sessionToken}`}; const cookie=(redeemed.res.headers.get('set-cookie')||'').split(';')[0]; const noCsrf=await j('/api/v4/partner/invitations',{method:'POST',headers:{cookie},body:JSON.stringify({email:'invitee@x.test',displayName:'Invitee',role:'partner_member'})}); assert.equal(noCsrf.res.status,403); const withCsrf=await j('/api/v4/partner/invitations',{method:'POST',headers:{cookie,'x-whole-story-csrf':redeemed.body.csrfToken},body:JSON.stringify({email:'invitee@x.test',displayName:'Invitee',role:'partner_member'})}); assert.equal(withCsrf.res.status,201);
const inbox=await j('/api/v4/partner/cases',{headers:bearer}); assert.equal(inbox.res.status,200); assert.equal(inbox.body.cases.length,1);
const accepted=await j(`/api/v4/partner/cases/${cid}/accept`,{method:'POST',headers:bearer,body:JSON.stringify({version:created.body.case.version})}); assert.equal(accepted.res.status,200); const stale=await j(`/api/v4/partner/cases/${cid}/assign`,{method:'POST',headers:bearer,body:JSON.stringify({version:created.body.case.version,partnerUserId:'ua'})}); assert.equal(stale.res.status,409); assert.equal(stale.body.error,'version_conflict');
const issueB=await issueMagicLink({user:ub,sessionStore:runtime.sessionStore,now:new Date()}); const redB=await j('/api/v4/partner/session/redeem',{method:'POST',body:JSON.stringify({token:issueB.token})}); const cross=await j(`/api/v4/partner/cases/${cid}`,{headers:{authorization:`Bearer ${redB.body.sessionToken}`}}); assert.ok([403,404].includes(cross.res.status)); assert.equal(JSON.stringify(cross.body).includes('Org A'),false);
server.close(); console.log('v4 api tests passed');
