import assert from 'node:assert/strict'; import {mkdtemp} from 'node:fs/promises'; import {join} from 'node:path'; import {tmpdir} from 'node:os';
import {createCaseStore,createPartnerStore,createEventStore} from '../server/v4/stores.js'; import {createCaseService} from '../server/v4/case-service.js';
const dir=await mkdtemp(join(tmpdir(),'ws-case-')); const caseStore=createCaseStore({filePath:join(dir,'cases.json')}); const partnerStore=createPartnerStore({filePath:join(dir,'partners.json')}); const eventStore=createEventStore({filePath:join(dir,'events.json')}); await partnerStore.upsertOrganization({id:'o1',name:'Org',resourceIds:['r1'],status:'active'});
const svc=createCaseService({caseStore,partnerStore,eventStore,now:()=>new Date('2026-09-23T10:00:00Z')});
const exact=svc.previewCase({story:{id:'s1',rawStory:'Private full story'},signals:[{domain:'food',status:'active',id:'sig1',label:'food',source:'detected',confidence:'high'}],priority:{priorityDomain:'food',title:'Food',why:'Need food'},profile:{displayName:'Private Name'},consent:{shareScope:'selected_fields',selectedFields:['signals']}}); assert.ok(Array.isArray(exact.sharePackage.signals)); assert.equal('profile' in exact.sharePackage,false); assert.equal('rawStory' in exact.sharePackage,false);
 const preview=svc.previewCase({story:{id:'s1',text:'I need food support'},signals:[{domain:'food',status:'active'}],priority:{domain:'food'},profile:{displayName:'J'},consent:{shareScope:'summary'}}); const created=await svc.createAndSendCase({...preview,resourceId:'r1',partnerOrgId:'o1',storyId:'s1',createdBy:{type:'person',id:null,displayName:'J'}}); assert.equal(created.caseRecord.status,'delivered'); assert.deepEqual(created.caseRecord.sharePackage,preview.sharePackage); assert.ok(created.accessSecret); assert.equal(created.events.map(e=>e.type).join(','),'case_created,case_sent,case_delivered');
await assert.rejects(svc.acceptCase({caseId:created.caseRecord.id,version:created.caseRecord.version,actor:{type:'person'}}),/FORBIDDEN/); const accepted=await svc.acceptCase({caseId:created.caseRecord.id,version:created.caseRecord.version,actor:{type:'partner',id:'u1',displayName:'A'}}); assert.equal(accepted.caseRecord.status,'accepted'); await assert.rejects(svc.assignCase({caseId:created.caseRecord.id,version:created.caseRecord.version,partnerUser:{id:'u1',displayName:'A'}}),e=>e.code==='VERSION_CONFLICT');
const closed=await svc.closeCase({caseId:created.caseRecord.id,version:accepted.caseRecord.version,actor:{type:'partner',id:'u1'},outcome:'no_availability',note:''}); assert.equal(closed.caseRecord.closedOutcome,'no_availability'); const confirmed=await svc.confirmPersonOutcome({caseId:created.caseRecord.id,version:closed.caseRecord.version,confirmed:false}); assert.equal(confirmed.caseRecord.closedOutcome,'no_availability'); assert.equal(confirmed.caseRecord.personConfirmedOutcome,false);
console.log('v4 case service tests passed');
// Final review: outcome confirmation must be an actual boolean, not truthy text.
await assert.rejects(
  svc.confirmPersonOutcome({caseId:created.caseRecord.id,version:confirmed.caseRecord.version,confirmed:'false'}),
  /confirmed_must_be_boolean/
);
