import assert from 'node:assert/strict'; import {mkdtemp} from 'node:fs/promises'; import {join} from 'node:path'; import {tmpdir} from 'node:os';
import {createServer} from '../server.js'; import {createV4Runtime} from '../server/v4/api.js'; import {issueMagicLink} from '../server/v4/auth.js'; import {deadEndFeedbackForCase} from '../shared-handoffs.mjs';
const dir=await mkdtemp(join(tmpdir(),'ws-v4-e2e-')); const runtime=createV4Runtime({dataDir:dir}); const iso=new Date().toISOString();
await runtime.partnerStore.upsertOrganization({id:'org-a',name:'Community Partner A',resourceIds:['food-a'],status:'active',createdAt:iso,updatedAt:iso}); await runtime.partnerStore.upsertOrganization({id:'org-b',name:'Community Partner B',resourceIds:['food-b'],status:'active',createdAt:iso,updatedAt:iso});
const manager=await runtime.partnerStore.upsertUser({id:'manager-a',partnerOrgId:'org-a',email:'manager-a@example.test',displayName:'Sarah Manager',role:'partner_manager',status:'active',createdAt:iso,updatedAt:iso}); const member=await runtime.partnerStore.upsertUser({id:'member-a',partnerOrgId:'org-a',email:'member-a@example.test',displayName:'Lee Member',role:'partner_member',status:'active',createdAt:iso,updatedAt:iso}); const managerB=await runtime.partnerStore.upsertUser({id:'manager-b',partnerOrgId:'org-b',email:'manager-b@example.test',displayName:'Other Manager',role:'partner_manager',status:'active',createdAt:iso,updatedAt:iso});
const server=createServer({v4Runtime:runtime}); await new Promise(r=>server.listen(0,'127.0.0.1',r)); const base=`http://127.0.0.1:${server.address().port}`;
async function j(path,{method='GET',body,headers={}}={}){const res=await fetch(base+path,{method,headers:{accept:'application/json',...(body!==undefined?{'content-type':'application/json'}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});let data={};try{data=await res.json()}catch{}return{res,data}}
async function createPersonCase(resourceId='food-a'){const preview=(await j('/api/v4/cases/preview',{method:'POST',body:{story:{id:'story-1',text:'I need food support and transportation help.'},signals:[{domain:'food',status:'active'}],priority:{priorityDomain:'food'},profile:{displayName:'Jay',preferredContactMethod:'phone'},consent:{shareScope:'summary'},resourceId,partnerOrgId:'org-a'}})).data;const created=await j('/api/v4/cases',{method:'POST',body:{sharePackage:preview.sharePackage,shareScope:preview.shareScope,personDisplayName:preview.personDisplayName,preferredContactMethod:preview.preferredContactMethod,storyId:'story-1',resourceId,partnerOrgId:'org-a',createdBy:{type:'person',id:null,displayName:'Jay'}}});assert.equal(created.res.status,201);assert.equal(created.data.case.status,'delivered');assert.ok(created.data.accessSecret);return created.data}
try{
 const created=await createPersonCase(); const id=created.case.id; const personHeaders={authorization:`Bearer ${created.accessSecret}`};
 const invite=await issueMagicLink({user:manager,sessionStore:runtime.sessionStore,now:new Date()}); const login=await j('/api/v4/partner/session/redeem',{method:'POST',body:{token:invite.token}});assert.equal(login.res.status,200);const partnerHeaders={authorization:`Bearer ${login.data.sessionToken}`};
 const replay=await j('/api/v4/partner/session/redeem',{method:'POST',body:{token:invite.token}});assert.equal(replay.res.status,400);
 const inbox=await j('/api/v4/partner/cases',{headers:partnerHeaders});assert.ok(inbox.data.cases.some(c=>c.id===id));
 const caseDetail=await j(`/api/v4/partner/cases/${id}`,{headers:partnerHeaders});assert.equal(caseDetail.res.status,200);assert.ok(caseDetail.data.assignableUsers.some(u=>u.id===member.id));
 const accepted=await j(`/api/v4/partner/cases/${id}/accept`,{method:'POST',headers:partnerHeaders,body:{version:created.case.version}});assert.equal(accepted.res.status,200);assert.equal(accepted.data.case.status,'accepted');
 const stale=await j(`/api/v4/partner/cases/${id}/assign`,{method:'POST',headers:partnerHeaders,body:{version:created.case.version,partnerUserId:member.id}});assert.equal(stale.res.status,409);assert.equal(stale.data.error,'version_conflict');assert.equal(stale.data.case.status,'accepted');
 const assigned=await j(`/api/v4/partner/cases/${id}/assign`,{method:'POST',headers:partnerHeaders,body:{version:accepted.data.case.version,partnerUserId:member.id}});assert.equal(assigned.res.status,200);assert.equal(assigned.data.case.ownerDisplayName,'Lee Member');
 const next=await j(`/api/v4/partner/cases/${id}/next-action`,{method:'POST',headers:partnerHeaders,body:{version:assigned.data.case.version,nextAction:'Call Jay',dueAt:new Date(Date.now()+3600_000).toISOString(),responsibleParty:'partner'}});assert.equal(next.res.status,200);
 const pmsg=await j(`/api/v4/cases/${id}/messages`,{method:'POST',headers:personHeaders,body:{body:'Phone works best after 3 PM.'}});assert.equal(pmsg.res.status,201);
 const reqInfo=await j(`/api/v4/partner/cases/${id}/request-information`,{method:'POST',headers:partnerHeaders,body:{fields:['preferred callback window']}});assert.equal(reqInfo.res.status,201);
 const partnerMessages=await j(`/api/v4/partner/cases/${id}/messages`,{headers:partnerHeaders});assert.equal(partnerMessages.res.status,200);assert.ok(partnerMessages.data.messages.some(m=>m.body==='Phone works best after 3 PM.'));assert.ok(partnerMessages.data.messages.some(m=>m.systemGenerated&&/preferred callback window/i.test(m.body)));
 const personMessages=await j(`/api/v4/cases/${id}/messages`,{headers:personHeaders});assert.equal(personMessages.res.status,200);assert.ok(personMessages.data.messages.some(m=>m.systemGenerated&&/preferred callback window/i.test(m.body)));
 const shared=await j(`/api/v4/cases/${id}/share`,{method:'POST',headers:personHeaders,body:{fields:{'preferred callback window':'after 3 PM'}}});assert.equal(shared.res.status,201);
 const scheduledAt=new Date(Date.now()+86400_000).toISOString(); const scheduled=await j(`/api/v4/partner/cases/${id}/schedule`,{method:'POST',headers:partnerHeaders,body:{version:next.data.case.version,scheduledAt}});assert.equal(scheduled.res.status,200);assert.equal(scheduled.data.case.status,'scheduled');
 const closed=await j(`/api/v4/partner/cases/${id}/close`,{method:'POST',headers:partnerHeaders,body:{version:scheduled.data.case.version,outcome:'service_completed',note:'Connected successfully'}});assert.equal(closed.res.status,200);assert.equal(closed.data.case.closedOutcome,'service_completed');
 const confirmed=await j(`/api/v4/cases/${id}/confirm-outcome`,{method:'POST',headers:personHeaders,body:{version:closed.data.case.version,confirmed:true,note:'Help happened'}});assert.equal(confirmed.res.status,200);assert.equal(confirmed.data.case.personConfirmedOutcome,true);
 const events=await j(`/api/v4/partner/cases/${id}/events`,{headers:partnerHeaders});const types=events.data.events.map(e=>e.type);for(const required of ['case_created','case_sent','case_delivered','case_accepted','case_assigned','next_action_set','message_posted','information_requested','information_shared','schedule_set','case_closed','person_outcome_confirmed'])assert.ok(types.includes(required),`missing ${required}`);for(let i=1;i<events.data.events.length;i++)assert.ok(new Date(events.data.events[i].at)>=new Date(events.data.events[i-1].at));
 const inviteB=await issueMagicLink({user:managerB,sessionStore:runtime.sessionStore,now:new Date()});const loginB=await j('/api/v4/partner/session/redeem',{method:'POST',body:{token:inviteB.token}});const cross=await j(`/api/v4/partner/cases/${id}`,{headers:{authorization:`Bearer ${loginB.data.sessionToken}`}});assert.equal(cross.res.status,404);assert.equal(JSON.stringify(cross.data).includes('Community Partner A'),false);
 const negative=await createPersonCase('food-a');const accepted2=await j(`/api/v4/partner/cases/${negative.case.id}/accept`,{method:'POST',headers:partnerHeaders,body:{version:negative.case.version}});const closed2=await j(`/api/v4/partner/cases/${negative.case.id}/close`,{method:'POST',headers:partnerHeaders,body:{version:accepted2.data.case.version,outcome:'no_availability',note:''}});assert.deepEqual(deadEndFeedbackForCase(closed2.data.case),{resourceId:'food-a',reason:'no_availability'});assert.equal(deadEndFeedbackForCase(closed.data.case),null);
 console.log('v4 e2e tests passed');
}finally{await new Promise(r=>server.close(r))}
