import {resolve} from 'node:path';
import {createCaseStore,createPartnerStore,createSessionStore,createMessageStore,createEventStore} from './stores.js';
import {createRemoteJsonStore} from './remote-json-store.js';
import {createCaseService} from './case-service.js'; import {createMessageService} from './message-service.js'; import {createAvailabilityService,availabilityFreshness} from './availability-service.js'; import {computeWorkflowFlags} from './sla.js';
import {issueMagicLink,redeemMagicLink,authenticatePartner,authenticateCaseSecret,requireCsrf,hashSecret} from './auth.js'; import {createRateLimiter} from './rate-limit.js';
import {readJson,sendJson} from '../api.js'; import {personProjection,partnerProjection} from '../../shared-handoffs.mjs';
function safeId(s){return String(s||'').replace(/[^A-Za-z0-9_.-]/g,'_')}
export function createV4Runtime({dataDir=process.env.WHOLE_STORY_DATA_DIR||resolve('.whole-story-data'),now=()=>new Date(),remoteStoreConfig=null}={}){
 const envRemote=process.env.WHOLE_STORY_STORE_URL&&process.env.WHOLE_STORY_STORE_KEY&&process.env.WHOLE_STORY_STORE_SECRET?{baseUrl:process.env.WHOLE_STORY_STORE_URL,apiKey:process.env.WHOLE_STORY_STORE_KEY,storageSecret:process.env.WHOLE_STORY_STORE_SECRET}:null;
 const remote=remoteStoreConfig||envRemote;
 const makeRemote=(documentKey,initialValue,validate)=>remote?createRemoteJsonStore({...remote,documentKey,initialValue,validate}):null;
 const arrayValid=v=>({ok:Array.isArray(v),errors:['array_required']});
 const partnerInitial={organizations:[],users:[],availability:[]},sessionInitial={magicLinks:[],sessions:[]};
 const caseStore=createCaseStore({filePath:resolve(dataDir,'cases.json'),store:makeRemote('cases',[],arrayValid)}),partnerStore=createPartnerStore({filePath:resolve(dataDir,'partners.json'),store:makeRemote('partners',partnerInitial,v=>({ok:v&&Array.isArray(v.organizations)&&Array.isArray(v.users)&&Array.isArray(v.availability),errors:['partner_store_invalid']}))}),sessionStore=createSessionStore({filePath:resolve(dataDir,'sessions.json'),store:makeRemote('sessions',sessionInitial,v=>({ok:v&&Array.isArray(v.magicLinks)&&Array.isArray(v.sessions),errors:['session_store_invalid']}))}),messageStore=createMessageStore({filePath:resolve(dataDir,'messages.json'),store:makeRemote('messages',[],arrayValid)}),eventStore=createEventStore({filePath:resolve(dataDir,'events.json'),store:makeRemote('events',[],arrayValid)});
 const caseService=createCaseService({caseStore,partnerStore,eventStore,now}); const messageService=createMessageService({messageStore,eventStore,getCase:id=>caseStore.getCase(id),now}); const availabilityService=createAvailabilityService({partnerStore,eventStore,now});
 return{dataDir,now,caseStore,partnerStore,sessionStore,messageStore,eventStore,caseService,messageService,availabilityService,limiters:{invite:createRateLimiter({limit:10,windowMs:3600_000}),redeem:createRateLimiter({limit:20,windowMs:10*60_000}),message:createRateLimiter({limit:60,windowMs:60_000})}};
}
function bad(message='invalid_request',code='INVALID_REQUEST'){const e=new Error(message);e.code=code;return e}
function only(body,allowed){for(const k of Object.keys(body||{}))if(!allowed.includes(k))throw bad(`unexpected_${k}`,'INVALID_BODY');return body||{}}
function routeMatch(path,re){return path.match(re)}
function requestKey(req,suffix=''){return `${req.socket?.remoteAddress||'local'}:${suffix}`}
async function partnerAuth(req,runtime,{mutation=false,manager=false}={}){const session=await authenticatePartner(req,{sessionStore:runtime.sessionStore,now:runtime.now()});if(mutation)requireCsrf(req,session);const user=await runtime.partnerStore.getUser(session.userId);if(!user||user.status==='revoked'||user.partnerOrgId!==session.partnerOrgId)throw bad('unauthorized','UNAUTHORIZED');if(manager&&user.role!=='partner_manager')throw bad('forbidden','FORBIDDEN');return{session,user}}
async function scopedPartnerCase(runtime,session,id){const c=await runtime.caseStore.getCase(id);if(!c||c.partnerOrgId!==session.partnerOrgId)throw bad('not_found','NOT_FOUND');return c}
async function personCase(req,runtime,id){const c=await runtime.caseStore.getCase(id);if(!c)throw bad('not_found','NOT_FOUND');try{authenticateCaseSecret(req,c)}catch{throw bad('not_found','NOT_FOUND')}return c}
function errorResponse(res,e){if(e?.code==='VERSION_CONFLICT')return sendJson(res,409,{error:'version_conflict',case:partnerProjection(e.current)});if(e?.code==='PAYLOAD_TOO_LARGE')return sendJson(res,413,{error:'request_too_large'});if(e?.code==='INVALID_JSON')return sendJson(res,400,{error:'invalid_json'});if(e?.code==='INVALID_BODY'||e?.code==='INVALID_REQUEST')return sendJson(res,400,{error:'invalid_request'});if(e?.code==='UNAUTHORIZED'||e?.message==='UNAUTHORIZED')return sendJson(res,401,{error:'unauthorized'});if(e?.code==='FORBIDDEN'||e?.message==='FORBIDDEN'||e?.message==='CSRF_REQUIRED')return sendJson(res,403,{error:'forbidden'});if(e?.code==='NOT_FOUND'||e?.message==='NOT_FOUND')return sendJson(res,404,{error:'not_found'});if(e?.message==='INVALID_OR_EXPIRED_TOKEN')return sendJson(res,400,{error:'invalid_or_expired_token'});if(e?.message==='future_sharing_withdrawn')return sendJson(res,409,{error:'future_sharing_withdrawn'});if(e?.message==='message_too_long')return sendJson(res,413,{error:'message_too_long'});if(e?.message==='destination_unavailable')return sendJson(res,409,{error:'destination_unavailable'});return sendJson(res,400,{error:safeId(e?.message||'request_failed').toLowerCase()})}
export async function handleV4Api(req,res,runtime){const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(!url.pathname.startsWith('/api/v4/'))return false;try{
 if(url.pathname==='/api/v4/cases/preview'&&req.method==='POST'){const body=only(await readJson(req),['story','signals','priority','profile','consent','resourceId','partnerOrgId']);const preview=runtime.caseService.previewCase(body);const org=body.partnerOrgId?await runtime.partnerStore.getOrganization(body.partnerOrgId):null;return sendJson(res,200,{...preview,resourceId:body.resourceId||null,partnerOrgId:body.partnerOrgId||null,destination:org?{id:org.id,name:org.name,status:org.status}:null})||true}
 if(url.pathname==='/api/v4/cases'&&req.method==='POST'){const body=only(await readJson(req),['sharePackage','shareScope','personDisplayName','preferredContactMethod','resourceId','partnerOrgId','storyId','createdBy']);const out=await runtime.caseService.createAndSendCase(body);return sendJson(res,201,{case:out.caseRecord,accessSecret:out.accessSecret})||true}
 let m=routeMatch(url.pathname,/^\/api\/v4\/cases\/([^/]+)$/);if(m&&req.method==='GET'){const c=await personCase(req,runtime,decodeURIComponent(m[1]));return sendJson(res,200,{case:personProjection(c),workflowFlags:computeWorkflowFlags(c,{now:runtime.now()})})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/cases\/([^/]+)\/(cancel|confirm-outcome|withdraw-sharing)$/);if(m&&req.method==='POST'){const c=await personCase(req,runtime,decodeURIComponent(m[1]));const body=await readJson(req);let out;if(m[2]==='cancel'){only(body,['version']);out=await runtime.caseService.cancelCase({caseId:c.id,version:body.version,actor:{type:'person',id:null}})}else if(m[2]==='confirm-outcome'){only(body,['version','confirmed','note']);out=await runtime.caseService.confirmPersonOutcome({caseId:c.id,version:body.version,confirmed:body.confirmed,note:body.note||''})}else{only(body,['version']);out=await runtime.caseService.withdrawFutureSharing({caseId:c.id,version:body.version})}return sendJson(res,200,{case:personProjection(out.caseRecord)})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/cases\/([^/]+)\/messages$/);if(m&&req.method==='GET'){const c=await personCase(req,runtime,decodeURIComponent(m[1]));const messages=await runtime.messageService.listAuthorizedMessages({caseId:c.id,authorize:x=>x.id===c.id,afterCursor:url.searchParams.get('after')});return sendJson(res,200,{messages})||true}
 if(m&&req.method==='POST'){const c=await personCase(req,runtime,decodeURIComponent(m[1]));const lim=runtime.limiters.message.take(requestKey(req,`person:${c.id}`));if(!lim.allowed){res.setHeader('Retry-After',String(lim.retryAfterSeconds));return sendJson(res,429,{error:'rate_limited'})||true}const body=only(await readJson(req),['body']);const message=await runtime.messageService.postMessage({caseId:c.id,actor:{type:'person',id:null,displayName:c.personDisplayName||null},body:body.body,authorize:x=>x.id===c.id});return sendJson(res,201,{message})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/cases\/([^/]+)\/share$/);if(m&&req.method==='POST'){const c=await personCase(req,runtime,decodeURIComponent(m[1]));const body=only(await readJson(req),['fields']);const event=await runtime.messageService.shareRequestedInformation({caseId:c.id,actor:{type:'person',id:null},fields:body.fields,authorize:x=>x.id===c.id});return sendJson(res,201,{event})||true}
 if(url.pathname==='/api/v4/partner/session/redeem'&&req.method==='POST'){const lim=runtime.limiters.redeem.take(requestKey(req,'redeem'));if(!lim.allowed){res.setHeader('Retry-After',String(lim.retryAfterSeconds));return sendJson(res,429,{error:'rate_limited'})||true}const body=only(await readJson(req),['token']);const out=await redeemMagicLink({token:body.token,sessionStore:runtime.sessionStore,partnerStore:runtime.partnerStore,now:runtime.now()});const secureCookie=Boolean(req.socket?.encrypted)||String(req.headers?.['x-forwarded-proto']||'').toLowerCase()==='https';res.setHeader('Set-Cookie',`ws_partner_session=${encodeURIComponent(out.sessionToken)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800${secureCookie?'; Secure':''}`);return sendJson(res,200,{sessionToken:out.sessionToken,csrfToken:out.csrfToken,user:{id:out.user.id,partnerOrgId:out.user.partnerOrgId,email:out.user.email,displayName:out.user.displayName,role:out.user.role},expiresAt:out.expiresAt})||true}
 if(url.pathname==='/api/v4/partner/session/logout'&&req.method==='POST'){const {session}=await partnerAuth(req,runtime,{mutation:true});await runtime.sessionStore.revokeSession(session.sessionHash);res.setHeader('Set-Cookie','ws_partner_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return sendJson(res,200,{ok:true})||true}
 if(url.pathname==='/api/v4/partner/invitations'&&req.method==='POST'){const lim=runtime.limiters.invite.take(requestKey(req,'invite'));if(!lim.allowed){res.setHeader('Retry-After',String(lim.retryAfterSeconds));return sendJson(res,429,{error:'rate_limited'})||true}const {session}=await partnerAuth(req,runtime,{mutation:true,manager:true});const body=only(await readJson(req),['email','displayName','role']);let user=await runtime.partnerStore.findUserByEmail(body.email);const now=new Date(runtime.now()).toISOString();user=await runtime.partnerStore.upsertUser({id:user?.id||`user_${Date.now().toString(36)}`,partnerOrgId:session.partnerOrgId,email:String(body.email||''),displayName:String(body.displayName||''),role:body.role==='partner_manager'?'partner_manager':'partner_member',status:'invited',createdAt:user?.createdAt||now,updatedAt:now});const issued=await issueMagicLink({user,sessionStore:runtime.sessionStore,now:runtime.now()});return sendJson(res,201,{invitation:{user:{id:user.id,email:user.email,displayName:user.displayName,role:user.role},token:issued.token,expiresAt:issued.expiresAt}})||true}
 if(url.pathname==='/api/v4/partner/cases'&&req.method==='GET'){const {session}=await partnerAuth(req,runtime);const cases=(await runtime.caseStore.listCasesByPartnerOrg(session.partnerOrgId)).map(c=>({...partnerProjection(c),workflowFlags:computeWorkflowFlags(c,{now:runtime.now()})}));return sendJson(res,200,{cases})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/partner\/cases\/([^/]+)$/);if(m&&req.method==='GET'){const {session,user}=await partnerAuth(req,runtime);const c=await scopedPartnerCase(runtime,session,decodeURIComponent(m[1]));const assignableUsers=user.role==='partner_manager'?(await runtime.partnerStore.listUsersByOrganization(session.partnerOrgId)).filter(x=>x.status==='active').map(x=>({id:x.id,displayName:x.displayName,role:x.role})):[];return sendJson(res,200,{case:partnerProjection(c),workflowFlags:computeWorkflowFlags(c,{now:runtime.now()}),assignableUsers})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/partner\/cases\/([^/]+)\/(accept|reject|assign|next-action|schedule|close)$/);if(m&&req.method==='POST'){const {session,user}=await partnerAuth(req,runtime,{mutation:true,manager:m[2]==='assign'});const c=await scopedPartnerCase(runtime,session,decodeURIComponent(m[1]));const body=await readJson(req);const who={type:'partner',id:user.id,displayName:user.displayName};let out;if(m[2]==='accept'){only(body,['version']);out=await runtime.caseService.acceptCase({caseId:c.id,version:body.version,actor:who})}if(m[2]==='reject'){only(body,['version','outcome','note']);out=await runtime.caseService.rejectCase({caseId:c.id,version:body.version,actor:who,outcome:body.outcome,note:body.note})}if(m[2]==='assign'){only(body,['version','partnerUserId']);const target=await runtime.partnerStore.getUser(body.partnerUserId);if(!target||target.partnerOrgId!==session.partnerOrgId||target.status!=='active')throw bad('not_found','NOT_FOUND');out=await runtime.caseService.assignCase({caseId:c.id,version:body.version,partnerUser:target})}if(m[2]==='next-action'){only(body,['version','nextAction','dueAt','responsibleParty']);out=await runtime.caseService.setNextAction({caseId:c.id,version:body.version,actor:who,nextAction:body.nextAction,dueAt:body.dueAt||null,responsibleParty:body.responsibleParty||'partner'})}if(m[2]==='schedule'){only(body,['version','scheduledAt']);out=await runtime.caseService.scheduleCase({caseId:c.id,version:body.version,actor:who,scheduledAt:body.scheduledAt})}if(m[2]==='close'){only(body,['version','outcome','note']);out=await runtime.caseService.closeCase({caseId:c.id,version:body.version,actor:who,outcome:body.outcome,note:body.note||''})}return sendJson(res,200,{case:partnerProjection(out.caseRecord)})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/partner\/cases\/([^/]+)\/messages$/);if(m&&req.method==='GET'){const {session}=await partnerAuth(req,runtime);const c=await scopedPartnerCase(runtime,session,decodeURIComponent(m[1]));const messages=await runtime.messageService.listAuthorizedMessages({caseId:c.id,authorize:x=>x.partnerOrgId===session.partnerOrgId,afterCursor:url.searchParams.get('after')});return sendJson(res,200,{messages})||true}if(m&&req.method==='POST'){const {session,user}=await partnerAuth(req,runtime,{mutation:true});const c=await scopedPartnerCase(runtime,session,decodeURIComponent(m[1]));const lim=runtime.limiters.message.take(requestKey(req,`partner:${user.id}`));if(!lim.allowed){res.setHeader('Retry-After',String(lim.retryAfterSeconds));return sendJson(res,429,{error:'rate_limited'})||true}const body=only(await readJson(req),['body']);const message=await runtime.messageService.postMessage({caseId:c.id,actor:{type:'partner',id:user.id,displayName:user.displayName},body:body.body,authorize:x=>x.partnerOrgId===session.partnerOrgId});return sendJson(res,201,{message})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/partner\/cases\/([^/]+)\/request-information$/);if(m&&req.method==='POST'){const {session,user}=await partnerAuth(req,runtime,{mutation:true});const c=await scopedPartnerCase(runtime,session,decodeURIComponent(m[1]));const body=only(await readJson(req),['fields']);const event=await runtime.messageService.requestInformation({caseId:c.id,actor:{type:'partner',id:user.id,displayName:user.displayName},fields:body.fields,authorize:x=>x.partnerOrgId===session.partnerOrgId});return sendJson(res,201,{event})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/partner\/cases\/([^/]+)\/events$/);if(m&&req.method==='GET'){const {session}=await partnerAuth(req,runtime);const c=await scopedPartnerCase(runtime,session,decodeURIComponent(m[1]));return sendJson(res,200,{events:await runtime.eventStore.listEvents(c.id,url.searchParams.get('after'))})||true}
 if(url.pathname==='/api/v4/partner/availability'&&req.method==='GET'){const {session,user}=await partnerAuth(req,runtime);const availability=await runtime.availabilityService.listAvailability(session.partnerOrgId);return sendJson(res,200,{user:{id:user.id,displayName:user.displayName,role:user.role},availability:availability.map(a=>({...a,freshness:availabilityFreshness(a,runtime.now())}))})||true}
 m=routeMatch(url.pathname,/^\/api\/v4\/partner\/availability\/([^/]+)$/);if(m&&req.method==='PUT'){const {session,user}=await partnerAuth(req,runtime,{mutation:true,manager:true});const body=only(await readJson(req),['state','expectedAvailableAt','eligibilityNote','serviceMode','languages','accessibilityNote']);const availability=await runtime.availabilityService.updateAvailability({partnerOrgId:session.partnerOrgId,partnerUser:user,resourceId:decodeURIComponent(m[1]),record:body});return sendJson(res,200,{availability})||true}
 return sendJson(res,404,{error:'not_found'})||true;
 }catch(e){errorResponse(res,e);return true}}
