import {createHash,randomBytes,timingSafeEqual} from 'node:crypto';
export const hashSecret=s=>createHash('sha256').update(String(s)).digest('hex');
const rand=()=>randomBytes(32).toString('base64url');
function eqHash(a,b){try{const aa=Buffer.from(String(a),'hex'),bb=Buffer.from(String(b),'hex');return aa.length===bb.length&&timingSafeEqual(aa,bb)}catch{return false}}
export function issueCaseAccessSecret(){const secret=rand();return{secret,hash:hashSecret(secret)}}
export async function issueMagicLink({user,sessionStore,now=new Date(),lifetimeMs=20*60_000}){const token=rand(),tokenHash=hashSecret(token);const expiresAt=new Date(new Date(now).getTime()+lifetimeMs).toISOString();await sessionStore.createMagicLink({id:cryptoRandomId(),tokenHash,userId:user.id,partnerOrgId:user.partnerOrgId,expiresAt,createdAt:new Date(now).toISOString(),redeemedAt:null,revokedAt:null});return{token,expiresAt}}
function cryptoRandomId(){return randomBytes(12).toString('hex')}
export async function redeemMagicLink({token,sessionStore,partnerStore,now=new Date()}){const link=await sessionStore.redeemMagicLink(hashSecret(token),now);let user=await partnerStore.getUser(link.userId);if(!user||user.status==='revoked'||user.partnerOrgId!==link.partnerOrgId)throw new Error('INVALID_OR_EXPIRED_TOKEN');if(user.status!=='active')user=await partnerStore.upsertUser({...user,status:'active',updatedAt:new Date(now).toISOString()});const sessionToken=rand(),csrfToken=rand();const expiresAt=new Date(new Date(now).getTime()+8*3600_000).toISOString();await sessionStore.createSession({id:cryptoRandomId(),sessionHash:hashSecret(sessionToken),csrfHash:hashSecret(csrfToken),userId:user.id,partnerOrgId:user.partnerOrgId,role:user.role,createdAt:new Date(now).toISOString(),lastSeenAt:new Date(now).toISOString(),idleExpiresAt:new Date(new Date(now).getTime()+2*3600_000).toISOString(),expiresAt,revokedAt:null});return{sessionToken,csrfToken,user,expiresAt}}
function cookies(header=''){return Object.fromEntries(String(header).split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(i<0?x:x.slice(0,i)),decodeURIComponent(i<0?'':x.slice(i+1))]}))}
export async function authenticatePartner(req,{sessionStore,now=new Date()}){const auth=String(req.headers?.authorization||'');let token,authMode='bearer';if(/^Bearer /i.test(auth))token=auth.slice(7).trim();else{token=cookies(req.headers?.cookie||'').ws_partner_session;authMode='cookie'}if(!token)throw new Error('UNAUTHORIZED');let session=await sessionStore.getSession(hashSecret(token),now);if(!session)throw new Error('UNAUTHORIZED');if(sessionStore.touchSession)session=await sessionStore.touchSession(session.sessionHash,now)||session;return{...session,authMode,rawSessionToken:token}}
export function requireCsrf(req,session){if(session.authMode!=='cookie')return true;const given=String(req.headers?.['x-whole-story-csrf']||'');if(!given||!eqHash(hashSecret(given),session.csrfHash))throw new Error('CSRF_REQUIRED');return true}
export function authenticateCaseSecret(req,caseRecord){const auth=String(req.headers?.authorization||'');const dedicated=String(req.headers?.['x-whole-story-case-secret']||'');const secret=/^Bearer /i.test(auth)?auth.slice(7).trim():dedicated;if(!secret||!caseRecord?.accessSecretHash||!eqHash(hashSecret(secret),caseRecord.accessSecretHash))throw new Error('UNAUTHORIZED');return true}
