import {randomBytes} from 'node:crypto'; import {issueCaseAccessSecret} from './auth.js'; import {transitionCase,validateClosure,validateSharePackage,personProjection,partnerProjection} from '../../shared-handoffs.mjs'; import {buildSharePackage} from '../../shared-referrals.mjs';
const id=p=>`${p}_${randomBytes(8).toString('hex')}`;
export function createCaseService({caseStore,partnerStore,eventStore,now=()=>new Date()}){
 const stamp=()=>new Date(now()).toISOString(); const actor=a=>a||{type:'system',id:null,displayName:null};
 const event=async(caseId,type,who,payload={})=>eventStore.appendEvent({id:id('evt'),caseId,type,actor:actor(who),at:stamp(),payload});
 async function update(caseId,version,fn,type,who,payload){const rec=await caseStore.updateCase(caseId,version,c=>({...fn(c),updatedAt:stamp()}));const ev=type?await event(caseId,type,who,typeof payload==='function'?payload(rec):payload||{}):null;return{caseRecord:rec,event:ev}}
 function previewCase({story={},signals=[],priority=null,profile={},consent={}}){const scope=consent.shareScope||'none';if(scope==='none')throw new Error('share_scope_required');const normalizedStory={...story,rawStory:story.rawStory??story.text??story.story??''};const sharePackage=buildSharePackage({story:normalizedStory,signals,priority:priority||{},profile,consent,alreadyTried:story.alreadyTried||[]});const check=validateSharePackage(sharePackage);if(!check.ok)throw new Error(check.errors.join(','));return{sharePackage,shareScope:scope,personDisplayName:profile.displayName||profile.name||null,preferredContactMethod:profile.preferredContactMethod||null}}
 async function createAndSendCase(input){const shareCheck=validateSharePackage(input.sharePackage);if(!shareCheck.ok)throw new Error(shareCheck.errors.join(','));const org=await partnerStore.getOrganization(input.partnerOrgId);if(!org||org.status!=='active')throw new Error('destination_unavailable');const t=stamp(),access=issueCaseAccessSecret();let rec={id:id('case'),publicCaseId:id('WS'),storyId:input.storyId||null,resourceId:input.resourceId,partnerOrgId:input.partnerOrgId,createdBy:input.createdBy||{type:'person',id:null,displayName:null},status:'sent',sharePackage:structuredClone(input.sharePackage),shareScope:input.shareScope||input.sharePackage.scope,personDisplayName:input.personDisplayName||null,preferredContactMethod:input.preferredContactMethod||null,ownerPartnerUserId:null,ownerDisplayName:null,nextAction:null,nextActionDueAt:null,scheduledAt:null,followUpAt:null,closedOutcome:null,closedNote:null,closedAt:null,personConfirmedOutcome:null,personConfirmedAt:null,futureSharingWithdrawn:false,accessSecretHash:access.hash,createdAt:t,updatedAt:t,version:1};await caseStore.createCase(rec);const e1=await event(rec.id,'case_created',rec.createdBy,{resourceId:rec.resourceId,shareScope:rec.shareScope});const e2=await event(rec.id,'case_sent',rec.createdBy,{partnerOrgId:rec.partnerOrgId});rec=await caseStore.updateCase(rec.id,1,c=>({...c,status:'delivered',updatedAt:stamp()}));const e3=await event(rec.id,'case_delivered',{type:'system',id:null,displayName:'Whole Story'},{partnerOrgId:rec.partnerOrgId});return{caseRecord:personProjection(rec),accessSecret:access.secret,events:[e1,e2,e3]}}
 async function getPersonCase({caseId}){return personProjection(await caseStore.getCase(caseId))}
 async function cancelCase({caseId,version,actor:who={type:'person'}}){return update(caseId,version,c=>transitionCase(c,'cancelled',{actorType:who.type==='partner'?'partner':'person',at:stamp()}),'case_cancelled',who)}
 async function partnerTransition(caseId,version,to,who,type,extra={}){if(who?.type!=='partner')throw new Error('FORBIDDEN');return update(caseId,version,c=>({...transitionCase(c,to,{actorType:'partner',at:stamp()}),...extra}),type,who)}
 const acceptCase=x=>partnerTransition(x.caseId,x.version,'accepted',x.actor,'case_accepted');
 const rejectCase=x=>partnerTransition(x.caseId,x.version,'rejected',x.actor,'case_rejected',{closedOutcome:x.outcome||'organization_declined'});
 async function assignCase({caseId,version,partnerUser}){return update(caseId,version,c=>({...c,ownerPartnerUserId:partnerUser.id,ownerDisplayName:partnerUser.displayName||null,status:c.status==='accepted'?'in_progress':c.status}),'case_assigned',{type:'partner',id:partnerUser.id,displayName:partnerUser.displayName},{ownerPartnerUserId:partnerUser.id})}
 async function setNextAction({caseId,version,actor:who,nextAction,dueAt,responsibleParty='partner'}){return update(caseId,version,c=>({...c,nextAction:String(nextAction||''),nextActionDueAt:dueAt||null,nextActionResponsibleParty:responsibleParty}),'next_action_set',who,{nextAction,dueAt,responsibleParty})}
 async function scheduleCase({caseId,version,actor:who,scheduledAt}){if(who?.type!=='partner')throw new Error('FORBIDDEN');return update(caseId,version,c=>({...transitionCase(c,'scheduled',{actorType:'partner',at:stamp()}),scheduledAt}),'schedule_set',who,{scheduledAt})}
 async function closeCase({caseId,version,actor:who,outcome,note=''}){if(who?.type!=='partner')throw new Error('FORBIDDEN');const check=validateClosure(outcome,note);if(!check.ok)throw new Error(check.errors.join(','));return update(caseId,version,c=>({...transitionCase(c,'closed',{actorType:'partner',at:stamp()}),closedOutcome:outcome,closedNote:note||null,closedAt:stamp()}),'case_closed',who,{outcome,note:note||null})}
 async function confirmPersonOutcome({caseId,version,confirmed,note=''}){if(typeof confirmed!=='boolean')throw new Error('confirmed_must_be_boolean');const current=await caseStore.getCase(caseId);if(!current||current.status!=='closed')throw new Error('outcome_confirmation_requires_closed_case');return update(caseId,version,c=>({...c,personConfirmedOutcome:confirmed,personConfirmedAt:stamp(),personConfirmationNote:note||null}),'person_outcome_confirmed',{type:'person',id:null},{confirmed,note:note||null})}
 async function withdrawFutureSharing({caseId,version}){return update(caseId,version,c=>({...c,futureSharingWithdrawn:true}),'future_sharing_withdrawn',{type:'person',id:null},{})}
 return{previewCase,createAndSendCase,getPersonCase,cancelCase,acceptCase,rejectCase,assignCase,setNextAction,scheduleCase,closeCase,confirmPersonOutcome,withdrawFutureSharing,partnerProjection};
}
